#!/usr/bin/env python3
"""Regenerate tests/fixtures/canonical-fixtures.json — the golden JCS/contentDigest
fixtures shared with the app (CAR-TERTests/Fixtures/canonical-fixtures.json).

Inputs are JSON *text* (so number parsing is part of the contract). Outputs come
from carterkit.canonical; the RFC 8785 vectors in tests/test_canonical.py pin that
implementation independently. After regenerating, copy the file verbatim:

    cp tests/fixtures/canonical-fixtures.json \\
       ../CAR-TER/CAR-TERTests/Fixtures/canonical-fixtures.json

Run with the venv: carterkit/.venv/bin/python scripts/gen-canonical-fixtures.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from carterkit import canonical as c  # noqa: E402

CANONICAL = {
    "literals": '[null, true, false]',
    "empty-containers": '{"a": {}, "b": [], "c": [{}, []]}',
    "integers": '[0, -0, 1, -1, 42, 100, 1000000, 9007199254740992, 9007199254740993, 1E2]',
    "floats": '[4.50, 0.1, 0.30000000000000004, 123.456, -1.5e-10, 2e-3, 1.0, -0.0]',
    "exponent-boundaries": '[1e20, 1e21, 1e-6, 1e-7, 0.000001, 0.0000001, 1.2345e21, 1e16, 1e+30]',
    "float-extremes": '[5e-324, -5e-324, 1.7976931348623157e308, 2.2250738585072014e-308]',
    "rfc8785-numbers": '[333333333.33333329, 1E30, 4.50, 2e-3, 0.000000000000000000000000001]',
    "string-escapes": r'["\u0000\u0001\u001f", "\b\t\n\f\r", "quote \" backslash \\ slash \/", "\u007f"]',
    "unicode-strings": r'["café", "€$", "😀 grin", "דּ", "日本語"]',
    "unicode-key-order": (r'{"€":"Euro Sign","\r":"Carriage Return",'
                          r'"דּ":"Hebrew Letter Dalet With Dagesh","1":"One",'
                          r'"😀":"Emoji: Grinning Face","\u0080":"Control",'
                          r'"ö":"Latin Small Letter O With Diaeresis"}'),
    "key-order-ascii": '{"b": 1, "a": 2, "B": 3, "A": 4, "aa": 5, "_": 6, "0": 7, "": 8}',
    "nested": ('{"z": {"y": [3, {"c": true, "b": null, "a": [1.5, "x"]}], "x": {}},'
               ' "a": [[[]], {"k": {"k": {"k": 0.5}}}]}'),
    "whitespace": ' {\n\t"a" : [ 1 , 2 ] ,\r\n "b" : { } \n} ',
}

TEMPLATE = {
    "id": "8C1F6A0E-2B7D-4B8E-9E1A-5D2C3B4A1F00",
    "title": "Fern",
    "schemaVersion": 1,
    "connection": {"url": "wss://connect.example.net/ws", "mode": "room",
                   "identity": {"name": "phone", "channel": "plants", "role": "client"}},
    "sources": {"weather": {"kind": "http", "url": "https://api.example.com/v1",
                            "interval": 600.0}},
    "tabs": [{"title": "Plants", "icon": "leaf", "grid": {"cols": 4, "rows": 6},
              "children": [{"id": "fern", "type": "label", "label": "Fern: last watered",
                            "position": [0, 0], "span": [1, 4]},
                           {"id": "water", "type": "button", "label": "Watered now",
                            "position": [1, 0], "span": [1, 2]}]}],
}


def _with(base, **patch):
    doc = json.loads(json.dumps(base))
    for path, value in patch.items():
        keys = path.split("__")
        node = doc
        for k in keys[:-1]:
            node = node.setdefault(k, {})
        node[keys[-1]] = value
    return doc


DIGEST = [
    ("template-plain", None, TEMPLATE),
    ("template-user-a-token", "same-template",
     _with(TEMPLATE, connection__token="tok-AAAA-user-a", connection__e2eeKey="a2V5LWE=")),
    ("template-user-b-token", "same-template",
     _with(TEMPLATE, connection__token="tok-BBBB-user-b", connection__e2eeKey="a2V5LWI=")),
    ("template-no-token", "same-template", TEMPLATE),
    ("template-source-credentials", "same-template",
     _with(TEMPLATE, sources__weather__username="me", sources__weather__password="hunter2",
           sources__weather__token="abc", sources__weather__headers={"X-Key": "k"})),
    ("template-provenance-editor", "same-template",
     _with(TEMPLATE, provenance={"parents": [{"id": "tpl-fern", "relation": "copy",
                                              "digest": "sha256:" + "0" * 64}]},
           attestations=[{"issuer": "carter", "sig": "xyz"}],
           extensions__editor={"zoom": 1.5, "selected": "fern"})),
    ("template-extensions-kept", None, _with(TEMPLATE, extensions={"editor": {"z": 1}, "kiosk": {"on": True}})),
    ("template-edited-title", None, _with(TEMPLATE, title="Fern (mine)")),
]


def main() -> None:
    out = {
        "_about": ("Golden RFC 8785 (JCS) + layout contentDigest fixtures. Source of truth: "
                   "carterkit/tests/fixtures/canonical-fixtures.json, regenerated by "
                   "carterkit/scripts/gen-canonical-fixtures.py and copied verbatim to "
                   "CAR-TER/CAR-TERTests/Fixtures/. Swift (LayoutDigest) and Python "
                   "(carterkit.canonical) must both reproduce every output byte for byte."),
        "canonical": [],
        "digest": [],
    }
    for name, text in CANONICAL.items():
        out["canonical"].append({"name": name, "input": text,
                                 "output": c.canonical_json(c.loads(text))})
    for name, group, doc in DIGEST:
        text = json.dumps(doc, indent=2, ensure_ascii=False)
        case = {"name": name, "input": text,
                "scope": c.canonical_json(c.digest_scope(doc)),
                "digest": c.content_digest(doc)}
        if group:
            case["group"] = group
        out["digest"].append(case)
    dest = ROOT / "tests" / "fixtures" / "canonical-fixtures.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {dest} ({len(out['canonical'])} canonical, {len(out['digest'])} digest)")


if __name__ == "__main__":
    main()
